// <auto-generated />
using System;
using MP.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MP.Infra.Migrations
{
    [DbContext(typeof(MapaProcessosDbContext))]
    partial class MapaProcessosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MP.Domain.Entities.Processo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdProcessoPai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcessoPai");

                    b.ToTable("Processos", (string)null);
                });

            modelBuilder.Entity("MP.Domain.Entities.Processo", b =>
                {
                    b.HasOne("MP.Domain.Entities.Processo", "ProcessoPai")
                        .WithMany("SubsProcessosNavigation")
                        .HasForeignKey("IdProcessoPai");

                    b.Navigation("ProcessoPai");
                });

            modelBuilder.Entity("MP.Domain.Entities.Processo", b =>
                {
                    b.Navigation("SubsProcessosNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
